### ISSUE TITLE
编译出来的APK是和com.topjohnwu.magisk  一样的，需要再安装你发布的APK才能修复环境获取suu?

### ISSUE THREAD

**Issue by 735394006** [4accccc/vivo-Magisk-suu#12]
编译出来的APK是和com.topjohnwu.magisk  一样的，用编译出来的apk修补  需要再安装你发布的APK才能修复环境获取suu?

**Comment by 4accccc** [comment]
你如果有兴趣可以自己把包名改了😎 后半句你可以再解释下吗，我有点看不懂🫨
