### ISSUE TITLE
就是下载不下来啊    implementation("com.github.4accccc.libsu:core:${vLibsu}")     implementation("com.github.4accccc.libsu:service:${vLibsu}")     implementation("com.github.4accccc.libsu:nio:${vLibsu}")

### ISSUE THREAD

**Issue by 735394006** [4accccc/vivo-Magisk-suu#13]
val vLibsu = "5.2.1"
    implementation("com.github.4accccc.libsu:core:${vLibsu}")
    implementation("com.github.4accccc.libsu:service:${vLibsu}")
    implementation("com.github.4accccc.libsu:nio:${vLibsu}")
Failed to resolve: com.github.4accccc.libsu:service:5.2.1
无法解析
![Uploading QQ截图20240316133033.jpg…]()

**Comment by 735394006** [comment]
![QQ截图20240316133033](https://github.com/4accccc/vivo-Magisk-suu/assets/36464540/c953b684-05f5-431c-867b-e733f30e2515)

**Comment by 4accccc** [comment]
把5.2.1改成5.1.1
也能用
有时间我再搞5.2.1😎




哥の世界你不懂(4a)
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "4accccc/vivo-Magisk-suu"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月16日(星期六) 中午1:32
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[4accccc/vivo-Magisk-suu] 就是下载不下来啊    implementation("com.github.4accccc.libsu:core:${vLibsu}")     implementation("com.github.4accccc.libsu:service:${vLibsu}")     implementation("com.github.4accccc.libsu:nio:${vLibsu}") (Issue #13)





 val vLibsu = "5.2.1" implementation("com.github.4accccc.libsu:core:${vLibsu}") implementation("com.github.4accccc.libsu:service:${vLibsu}") implementation("com.github.4accccc.libsu:nio:${vLibsu}")  
Failed to resolve: com.github.4accccc.libsu:service:5.2.1
 无法解析
