### ISSUE TITLE
fix touchscreen for gsi

### ISSUE THREAD

**Issue by ghost** [4accccc/vivo-Magisk-suu#17]
Device: Vivo Y52s
Android version:12L(API32)
Magisk version name:24.3_SUU
Magisk version code:24300

vivo y52s，底包funtouchos10.5安卓10，已解锁BL。但还是没有fastboot功能。底包用TIK4.0修改过boot.img删除了AVB和强制加密，修改了super.img中vendor.img.ext4，也去除了强制加密和AVB。没有twrp可刷。

用TIK4.0修改了super.img，把system.img给替换成了AndyYan GSI系统（BVN 安卓12L），刷进去，重启，此时用的最新版delta suu面具。发现屏幕触控驱动失效，完全不能触控，但可以用电脑scrapy远程控制，且其他功能均正常。

尝试了所有版本的magisk，只有这个24300suu能用触控。https://github.com/4accccc/vivo-Magisk-suu/releases/download/v24.3suu/app-release.apk 但这个不是delta版本，没有magisk hide，某些app检测root就闪退。只能遵守排除列表对付，效果很差，而且还不能刷shamiko，只要刷了shamiko立马被格机然后黑屏无显示无限重启，连救砖模块都失效了，rec也进不去，只能MTKClient深度刷机救砖（我提前备份过）

麻烦大佬把最新delta给修复一下，让其支持触控，谢谢！

**Comment by 4accccc** [comment]
这些东西得等我放暑假了才有时间搞，
另附，gsi可以用原版的su授权，没必要用suu。

**Comment by 123z45** [comment]
好的，谢谢~
不过我手机无论是gsi下还是原厂系统下用delta su版本均不开机。Apatch是能开机不能用的状态。发现一个特殊的：Termux下执行任意路径/su均会返回operation-not-permitted,不管那个su文件真假，甚至都不判断它存不存在。也许是我这个底包不行的原因吧（2023年11月最新版），有时间了找个最低版本的funtouchos刷机包，单提取boot.img修补刷上，再刷GSI看看
```
u0_a135@localhost~$ mkdir test
u0_a135@localhost~$ ls -alh test
total 7.0K
drwx------ 2 u0_a135 u0_a135 3.5K May  2 20:55 .
drwx------ 6 u0_a135 u0_a135 3.5K May  2 20:55 ..
u0_a135@localhost~$ test/su
bash: test/su: Operation not permitted
u0_a135@localhost~$ echo "echo TestOK">test/su;chmod +x test/su;test/su;mv test/su test/ceshi.sh;test/ceshi.sh
bash: test/su: Operation not permitted
TestOK
u0_a135@localhost~$ /1/2/3/su
bash: /1/2/3/su: Operation not permitted
u0_a135@localhost~$ /456/789/su
bash: /456/789/su: Operation not permitted
u0_a135@localhost~$ su
bash: /data/data/com.termux/files/usr/bin/su: /data/data/com.termux/files/usr/bin/sh: bad interpreter: Operation not permitted
u0_a135@localhost~$ /sbin/su --version;/sbin/suu --version;file /sbin/su;file /sbin/suu
bash: /sbin/su: Operation not permitted
24.3:MAGISKSUU
/sbin/su: cannot open `/sbin/su' (No such file or directory)
/sbin/suu: symbolic link to ./magisk
```

**Comment by 4accccc** [comment]
> ## 此方法适用于GSI，但是不支持sGSI。必须使用Kitsune Mask(官方版本Kitsune和suu版本均可，官方版本的提权命令是`/sbin/magisk su`，suu版本的是`/sbin/suu` )，使用绿色logo的magisk无效。
> [空模块.zip](https://github.com/user-attachments/files/16777559/default.zip)
> 
> 刷gsi之前提前把/oem/vendor.prop提取出来，复制里面的所有内容到这个空模块的system.prop里面，然后，把system.prop里面两行带有internet.name和market.name的删了，保存。modules.prop自定义一下，
> 
> ```
> id=<数字+字母+下划线>
> name=<面具管理器里面显示的模块名字，随便填写>
> version=1.0
> versionCode=1
> author=<作者，随便填>
> description=<描述，随便写>
> ```
> 
> 刷完gsi连接电脑，用scrcpy远程控制，激活，进入桌面，安装kitsune mask app，修复环境，重启后仍然用电脑scrcpy远程控制，安装改好的模块(不要直接用我发的，我发的是空模块)，重启触控就能用了

感谢！我有时间拿我的vivo机子试下

**Comment by 1q23lyc45** [comment]
没事哈~
不保证所有手机能用，我测试Vivo Y52s 可以用。
