### ISSUE TITLE
vivo设备dd命令没有权限

### ISSUE THREAD

**Issue by MickWu7** [4accccc/vivo-Magisk-suu#19]
刷入了magisk，使用suu可以获取root权限
执行dd if=/dev/block/sdc48 of=/sdcard/a.img报错没有权限，具体如下所示:
PD2230:/ $ suu
PD2230:/ # dd if=/dev/block/sdc48 of=/sdcard/a.img
dd: /dev/block/sdc48: Permission denied
0+0 records in
0+0 records out
0 bytes (0 B) copied, 0.000143 s, 0 B/s
1|PD2230:/ # readlink /dev/block/by-name/boot
/dev/block/sdc48

**Comment by MickWu7** [comment]
主要目的是：将原生的boot进行备份，并且后期可以不通过fastboot刷入boot.img

**Comment by 4accccc** [comment]
不能提取boot是发哥限制，无法绕过。
不然你可以试试提取除boot之外的分区，保证正常。

**Comment by MickWu7** [comment]
其他的确实可以，是联发科芯片导致的吗？小米同样联发科的设备是可以提取boot的，可以通过修改sepolicy来实现吗？求教

**Comment by MickWu7** [comment]
@4accccc 求教大佬指点
