### ISSUE TITLE
无法隐藏root

### ISSUE THREAD

**Issue by 1q23lyc45** [4accccc/vivo-Magisk-suu#20]
这个仓库的Magisk SUU除24.3版本外全部无法启动，卡vivo logo无限重启。
https://github.com/4accccc/vivo-Magisk-Delta-suu/releases 这个版本可以开机

24.3版本排除列表失效，Shamiko 安装不上，Hunter红色提示黑产设备，已被Hook&修改

Delta(Kitsune) SUU版本，虽然不配置就自带一些隐藏，但是Hunter仍提示蓝色风险设备，找到Magisk /system/bin/magisk和/sbin/magisk。开MagiskHide无法隐藏/system/bin/magisk，只隐藏了/sbin/magisk。

Momo哪个版本都过不了，提示找到Magisk，只有这一条。BL未锁那个不用隐藏。

**Comment by 4accccc** [comment]
卡重启是每个手机不同体质
24.3shamiko肯定装不上 排除列表开了没shamiko有球用
hunter本来就不好过
找到magisk是你自己的问题 我这边手机环境一塌糊涂就是没有找到magisk(delta最新R6687BB53)
![Screenshot_20240724_083102](https://github.com/user-attachments/assets/4c65b3dc-8279-4cd8-9b90-0b272f312fc4)
